### ISSUE TITLE
SyntaxError: Unexpected token ... reporter\script.js:7

### ISSUE THREAD

**Issue by HItesh007** [maciejmaciejewski/azure-pipelines-cucumber#21]
I am getting this error while using the plugin in azure pipeline. Please find full stack trace below.

```
C:\hostedtoolcache\windows\node\6.17.1\x64\node.exe" script.js
D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\script.js:7
  ...(rawMetadata && {
  ^^^
##[warning]Error: Failed to run script
##[debug]Processed: ##vso[task.issue type=warning;]Error: Failed to run script

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
##[debug]task result: SucceededWithIssues
##[debug]Processed: ##vso[task.complete result=SucceededWithIssues;]
Finishing: Publish Cucumber HTML Report
```

**Comment by maciejmaciejewski** [comment]
hello @HItesh007 
Most probably you are using deprecated version 6 of NodeJS, spread operator mentioned in the error was introduced in version 8. Please make sure you use most recent version of Node for running it.


You can use below snippet to run it before my extension
```
steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

```

**Comment by HItesh007** [comment]
@maciejmaciejewski ,

I have updated the version of Node js to 10.x and it's now working. Marking this as closed.
