### ISSUE TITLE
Publishing Reporting

### ISSUE THREAD

**Issue by sthorson1222** [maciejmaciejewski/azure-pipelines-cucumber#27]
There is a abit of issue i am having is, i have the same project in a two different build pipeline, one is succesful and other one is not and this is log here below:

-------

2021-01-04T22:30:50.0277001Z ##[section]Starting: Publish Cucumber Report
2021-01-04T22:30:50.0503586Z ==============================================================================
2021-01-04T22:30:50.0503954Z Task         : Publish Cucumber Report
2021-01-04T22:30:50.0504219Z Description  : Publish Cucumber Report
2021-01-04T22:30:50.0504430Z Version      : 1.0.6
2021-01-04T22:30:50.0504668Z Author       : Maciej Maciejewski
2021-01-04T22:30:50.0504944Z Help         : Replace with markdown to show in help
2021-01-04T22:30:50.0505261Z ==============================================================================
2021-01-04T22:30:51.1115101Z [command]C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" install"
2021-01-04T22:30:59.2120662Z npm notice created a lockfile as package-lock.json. You should commit this file.
2021-01-04T22:30:59.2121273Z npm WARN reporter No description
2021-01-04T22:30:59.2121914Z npm WARN reporter No repository field.
2021-01-04T22:30:59.2122316Z npm WARN reporter No license field.
2021-01-04T22:30:59.2122652Z 
2021-01-04T22:30:59.2123024Z added 22 packages from 53 contributors and audited 22 packages in 3.702s
2021-01-04T22:30:59.2123483Z found 0 vulnerabilities
2021-01-04T22:30:59.2123697Z 
2021-01-04T22:30:59.2429238Z Found 0 matching D:/a/1/s pattern
2021-01-04T22:30:59.3005917Z [command]"C:\Program Files\nodejs\node.exe" script.js
2021-01-04T22:30:59.7758568Z D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\node_modules\cucumber-html-reporter\lib\jsonDir.js:26
2021-01-04T22:30:59.7759723Z             throw new Error('Invalid Cucumber JSON file found under ' + options.jsonDir + ': ' + file);
2021-01-04T22:30:59.7761500Z             ^
2021-01-04T22:30:59.7761736Z 
2021-01-04T22:30:59.7762167Z Error: Invalid Cucumber JSON file found under D:/a/1/s: D:\a\1\s\.vs\ProjectSettings.json
2021-01-04T22:30:59.7763979Z     at mergeJSONS (D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\node_modules\cucumber-html-reporter\lib\jsonDir.js:26:19)
2021-01-04T22:30:59.7764798Z     at Array.map (<anonymous>)
2021-01-04T22:30:59.7765332Z     at Object.collectJSONS (D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\node_modules\cucumber-html-reporter\lib\jsonDir.js:48:11)
2021-01-04T22:30:59.7766148Z     at Object.generate (D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\node_modules\cucumber-html-reporter\lib\reporter.js:507:17)
2021-01-04T22:30:59.7767589Z     at generateReport (D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\node_modules\cucumber-html-reporter\index.js:30:21)
2021-01-04T22:30:59.7768536Z     at Object.<anonymous> (D:\a\_tasks\PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287\1.0.6\reporter\script.js:20:1)
2021-01-04T22:30:59.7769036Z     at Module._compile (internal/modules/cjs/loader.js:1063:30)
2021-01-04T22:30:59.7769407Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
2021-01-04T22:30:59.7770330Z     at Module.load (internal/modules/cjs/loader.js:928:32)
2021-01-04T22:30:59.7770680Z     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
2021-01-04T22:30:59.7807074Z ##[warning]Error: Failed to run script
2021-01-04T22:30:59.7925303Z ##[section]Finishing: Publish Cucumber Report

**Comment by maciejmaciejewski** [comment]
Hey there,

This is a known third party library issue, please refer to #16 for more details.

Regards,
Maciej
