### ISSUE TITLE
Unexpected Token error in the azure pipelines task

### ISSUE THREAD

**Issue by himkumar1990** [maciejmaciejewski/azure-pipelines-cucumber#39]
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)

Getting above error in the PublishCucumberReport . Please let me know if further information needed

**Comment by maciejmaciejewski** [comment]
If you please could provide some more details that would be very helpful.
