### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by vitoralmeidatests** [maciejmaciejewski/azure-pipelines-cucumber#52]
Hi,
I´m having this error when publishing the report. It may be from my response body on a request being too big?

Is there a maximum size for a response?
Any idea of how to fix this?

Thanks

**Comment by maciejmaciejewski** [comment]
@vitoralmeidatests 
Reports are attached via internal AzureDevops tools so there might be a limit set there.
Can you please post some logs so I can get more details?

**Comment by vitoralmeidatests** [comment]
[log.txt](https://github.com/maciejmaciejewski/azure-pipelines-cucumber/files/8366118/log.txt)

@maciejmaciejewski here it is

**Comment by rmatthaiasos** [comment]
Hello @maciejmaciejewski ,

Same error seems to be still reproducible (1.0.12). Here are some logs:
```2025-02-18T04:01:23.6461888Z npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
2025-02-18T04:01:23.6587267Z Found 1 matching /home/vsts/work/r1/a/_ui-partners-test-suite.git/target/reports/cucumber/ pattern
2025-02-18T04:01:23.6589583Z Processing /home/vsts/work/r1/a/_ui-partners-test-suite.git/target/reports/cucumber/report.json
2025-02-18T04:01:24.1029196Z Saving modified report as /home/vsts/work/r1/a/_ui-partners-test-suite.git/target/reports/cucumber/report.json
2025-02-18T04:01:25.0298388Z [command]/usr/local/bin/node script.js
2025-02-18T04:01:27.9774897Z /home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:14
2025-02-18T04:01:27.9775761Z const isBase64 = (data) => /^(?:[A-Z0-9+\/]{4})*(?:[A-Z0-9+\/]{2}==|[A-Z0-9+\/]{3}=|[A-Z0-9+\/]{4})$/i.test(data);
2025-02-18T04:01:27.9778679Z ##[warning]Error: Failed to run script
2025-02-18T04:01:27.9787815Z                                                                                                        ^
2025-02-18T04:01:27.9788132Z 
2025-02-18T04:01:27.9788400Z RangeError: Maximum call stack size exceeded
2025-02-18T04:01:27.9788664Z     at RegExp.test (<anonymous>)
2025-02-18T04:01:27.9789499Z     at isBase64 (/home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:14:104)
2025-02-18T04:01:27.9790025Z     at /home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:280:37
2025-02-18T04:01:27.9790404Z     at Array.forEach (<anonymous>)
2025-02-18T04:01:27.9790772Z     at /home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:268:41
2025-02-18T04:01:27.9791164Z     at Array.forEach (<anonymous>)
2025-02-18T04:01:27.9791532Z     at /home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:266:31
2025-02-18T04:01:27.9791924Z     at Array.forEach (<anonymous>)
2025-02-18T04:01:27.9792290Z     at /home/vsts/work/_tasks/PublishCucumberReport_83c082c0-5032-11ea-8fab-bbe0f0fcf287/1.0.12/reporter/node_modules/cucumber-html-reporter/lib/reporter.js:251:30
2025-02-18T04:01:27.9792684Z     at Array.forEach (<anonymous>)
2025-02-18T04:01:27.9792878Z 
2025-02-18T04:01:27.9793117Z Node.js v18.20.6```
